baseURL = 'https://www.willmuseum.com'
languageCode = 'zh'
title = 'é—ä¹¦åšç‰©é¦†'
theme = "charaka-hugo-theme"
copyright = "&copy; <a href=\"https://github.com/viticis/will-museum\">WILL MUSEUM</a> ğŸ’” 2021"

[params]

[[params.social]]
  url = "https://github.com/viticis/will-museum"
  fa_icon = "fab fa-github"