baseURL = 'https://willmuseum.com'
languageCode = 'zh'
title = 'é—ä¹¦åšç‰©é¦†'
theme = "charaka-hugo-theme"
copyright = "&copy;2021 ğŸ’” Will Museum"

[params]

[[params.social]]
  url = "about"
  fa_icon = "fas fa-info"
[[params.social]]
  url = "https://github.com/viticis/will-museum"
  fa_icon = "fab fa-github"